### ISSUE TITLE
`n98-magerun2 sys:cron:run <...>`: «Argument 1 passed to N98\Magento\Command\System\Cron\AbstractCronCommand::getSchedule() must be of the type array, boolean given»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [tradefurniturecompany/site#127]
![01](https://user-images.githubusercontent.com/83204/75103600-f6591280-5626-11ea-97ad-b7f3a03b6d08.png)

**Comment by dmitry-fedyuk** [comment]
Fixed.

**Comment by MagicLegend** [comment]
Hey @dmitry-fedyuk!

I am running into the same error, could you give some insight on what changes to the BP module fixed the issue? Are the changes in 47a339d required? Or are 7ac9dc8 and f690a1a enough?

Thanks!
