### ISSUE TITLE
«Registry key "mgk_adcpopup_items" already exists at vendor/magento/framework/Registry.php:60»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [tradefurniturecompany/site#130]
```
[2020-02-28 21:24:27] main.CRITICAL: Registry key "mgk_adcpopup_items" already exists {"exception":"[object] (RuntimeException(code: 0): Registry key \"mgk_adcpopup_items\" already exists at /var/www/vhosts/tradefurniturecompany.co.uk/htdocs/vendor/magento/framework/Registry.php:60)"} []
```

**Comment by dmitry-fedyuk** [comment]
[2020-02-27 13:49:09] main.CRITICAL: Exception message: Registry key "mgk_adcpopup_items" already exists
Trace: <pre>#1 MageKey\AdcPopup\Observer\QuoteAddAfter->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:88]
#2 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:74]
#3 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Event/Manager.php:66]
#4 Magento\Framework\Event\Manager->dispatch() called at [generated/code/Magento/Framework/Event/Manager/Proxy.php:95]
#5 Magento\Framework\Event\Manager\Proxy->dispatch() called at [vendor/magento/module-quote/Model/Quote.php:1682]
#6 Magento\Quote\Model\Quote->addProduct() called at [vendor/magento/module-checkout/Model/Cart.php:379]
#7 Magento\Checkout\Model\Cart->addProduct() called at [vendor/magento/module-checkout/Model/Cart.php:287]
#8 Magento\Checkout\Model\Cart->addOrderItem() called at [vendor/magento/module-sales/Controller/AbstractController/Reorder.php:65]
#9 Magento\Sales\Controller\AbstractController\Reorder->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#10 Magento\Sales\Controller\Order\Reorder\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#11 Magento\Sales\Controller\Order\Reorder\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#12 Magento\Sales\Controller\Order\Reorder\Interceptor->___callPlugins() called at [generated/code/Magento/Sales/Controller/Order/Reorder/Interceptor.php:26]
#13 Magento\Sales\Controller\Order\Reorder\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#14 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#15 Magento\Sales\Controller\Order\Reorder\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#16 Magento\Sales\Controller\Order\Reorder\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#17 Magento\Sales\Controller\Order\Reorder\Interceptor->___callPlugins() called at [generated/code/Magento/Sales/Controller/Order/Reorder/Interceptor.php:39]
#18 Magento\Sales\Controller\Order\Reorder\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#19 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#20 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#21 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#22 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#23 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#24 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#25 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#26 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#27 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#28 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:137]
#29 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#30 Magento\Framework\App\Http\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#31 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#32 Magento\Framework\App\Http\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:26]
#33 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#34 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]

**Comment by dmitry-fedyuk** [comment]
It is caused by the `MageKey_AdcPopup` module.

**Comment by dmitry-fedyuk** [comment]
It leads to unability for a customer to reorder his previous order: «We can't add this item to your shopping basket right now»:
![01](https://user-images.githubusercontent.com/83204/75620333-b4dddf80-5bb1-11ea-8aee-32a793a2e95a.png)

**Comment by dmitry-fedyuk** [comment]
Fixed.

**Comment by kemoihoc** [comment]
Fixed below code:
app/code/MageKey/AdcPopup/Observer/QuoteAddAfter.php
public function execute(Observer $observer)
    {
        $items = $observer->getItems();
        $this->registry->unregister(DataHelper::REGISTER_ITEMS_KEY, $items);
        $this->registry->register(DataHelper::REGISTER_ITEMS_KEY, $items);
    }
