### ISSUE TITLE
This repository is public

### ISSUE THREAD

**Issue by perryholden** [tradefurniturecompany/site#272]
I found this repository while searching the web. As you might surmise, this is not a good thing. You need to change this repo's visibility to "private" as soon as possible. Have a great day.

**Comment by dmitrii-fediuk** [comment]
The repository does not contain any sensitive data.  
I do not believe in [security through obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity) and prefer [**open security**](https://en.wikipedia.org/wiki/Open_security) instead.
